### ISSUE TITLE
GE 44 Ton Crash 5.0.2

### ISSUE THREAD

**Issue by GlacierPark19** [Mrbrutal/Traincraft-5#109]
Hey Guys! Found this little crash after hitting attempting to start my yard switcher.

[crash-2021-05-21_16.21.49-server.txt](https://github.com/Traincraft/Traincraft/files/6525422/crash-2021-05-21_16.21.49-server.txt)

**Comment by GlacierPark19** [comment]
Edit: This crash occurs with ANY locomotive or other TC entity that use fuel. Once this crash has occurred the world becomes corrupted/ un playable. Uh oh! @EternalBlueFlame

**Comment by EternalBlueFlame** [comment]
Okay so good news, it looks like you're running either a dated build, or the curseforge build, which is like tripple dated. This particular bug was actually fixed some time ago, and doesn't effect current builds.
You can grab our pre-release builds here: https://nightly.link/EternalBlueFlame/Traincraft-5/workflows/gradle/1.7-TiM

i'm looking into the other bugs you reported as well, so no offense intended if i copy-paste this reply to other things it applies to.
