### ISSUE TITLE
Switch stand model glitching

### ISSUE THREAD

**Issue by GlacierPark19** [Mrbrutal/Traincraft-5#110]
Hello again!

While building my "yard" today, I discovered that the High star switch stand's model collides with the new switches when used. Also the more tracks you have, the worse your FPS. 
![2021-05-21_16 17 07](https://user-images.githubusercontent.com/55335173/119206782-01c90280-ba51-11eb-8760-77c19f3334b1.png)
![2021-05-21_16 17 09](https://user-images.githubusercontent.com/55335173/119206784-02fa2f80-ba51-11eb-932d-c2f4cdc98304.png)

**Comment by EternalBlueFlame** [comment]
This one is getting fixed in the next push, I didn't even think about this honestly, sorry about that, I'm so used to using rail skin 2 in the trainsinmotion.cfg file the mod generates.
