### ISSUE TITLE
Steam Loco not accepting water- TC 5.0.2

### ISSUE THREAD

**Issue by GlacierPark19** [Mrbrutal/Traincraft-5#111]
Me again ( I need a life lol)

While steaming up my Baldwin F-14, I discovered it will not accept water. Uh oh!
![2021-05-21_16 27 48](https://user-images.githubusercontent.com/55335173/119207001-9e8ba000-ba51-11eb-9456-97a7f0b80826.png)

![2021-05-21_16 27 52](https://user-images.githubusercontent.com/55335173/119206999-9df30980-ba51-11eb-96a8-966651e558aa.png)
![2021-05-21_16 27 55](https://user-images.githubusercontent.com/55335173/119207000-9e8ba000-ba51-11eb-9406-021148d7176a.png)

**Comment by EternalBlueFlame** [comment]
Thanks for the report, i'll take a look into this error and see what's going on. Weird that it's happening again, I could have sworn I patched this a while ago.

**Comment by EternalBlueFlame** [comment]
Okay so good news, it looks like you're running either a dated build, or the curseforge build, which is like tripple dated. This particular bug was actually fixed some time ago, and doesn't effect current builds.
You can grab our pre-release builds here: [https://nightly.link/EternalBlueFlame/Traincraft-5/workflows/gradle/1.7-TiM](https://nightly.link/EternalBlueFlame/Traincraft-5/workflows/gradle/1.7-TiM)

i'm looking into the other bugs you reported as well, so no offense intended if i copy-paste this reply to other things it applies to.
