### ISSUE TITLE
[1.7.10]Traincraft & Enviromine compatibility 

### ISSUE THREAD

**Issue by NicolaiSeven** [Mrbrutal/Traincraft-5#117]
There is client crash on SMP, when trying to use placed High Star Switch Stand.

https://pastebin.com/ChJB2R00

That crash called by if Enviromine installed. 
It also cause client crash on server, when try to use Overhead wires and other switches, stands.

Mod version: Traincraft-4.4.1_CE_2.0

**Comment by EternalBlueFlame** [comment]
Thanks for this report. I've submitted a fix for this to bidahochi for the next CE release.
The main git for CE releases is over here: https://github.com/bidahochi/Traincraft-5
