### ISSUE TITLE
small error in build.gradle

### ISSUE THREAD

**Issue by Tsoccerguy3** [Mrbrutal/Traincraft-5#20]
you need to add these 2 lines to build.gradle source so that Gradle will compile without a warning or error. see link below for the edit i posted in Forum
sourceCompatibility = 1.8
targetCompatibility = 1.8
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287038-traincraft-4-2-1?comment=3648

**Comment by canitzp** [comment]
I know this, but the 1.10.2 is not for compiling at this time. I add these lines if I want to compile it.
