### ISSUE TITLE
Idea!

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [Mrbrutal/Traincraft-5#30]
Anychance you can make the trains life size? the mod is great and everything... but having them so small ruins the fun

**Comment by TheProPlayer17** [comment]
but then you have to make the tracks huge!

**Comment by TheBritishBrotherhood** [comment]
Just like IRL then?

**Comment by canitzp** [comment]
bigger / real life sized trains and tracks don't keep the feeling of the default traincraft. There is another train mod called rails of war. Try this mod
