### ISSUE TITLE
Cant get resource railcraft

### ISSUE THREAD

**Issue by Mattizin** [Mrbrutal/Traincraft-5#31]
Hey,

i tried to get Traincraft in my workspace to learna  bit ;)
downladed the repo and did gradlew setupDecompWorkspace --refresh-dependencies
It stopped with the error that it coudlnt get the railcraft files which are a dependency in the build.gradle
Did the railcraft repository path changed or why does it crash there?

**Comment by canitzp** [comment]
It should work, I look into it later

**Comment by Mattizin** [comment]
![image](https://cloud.githubusercontent.com/assets/3749273/18815385/74c1a5a2-832f-11e6-86cc-e9cdd38cd6bb.png)
Thats the error im getting fyi :)

**Comment by CovertJaguar** [comment]
The blog should be back up, but I have idea how that would have affected ivy.

**Comment by canitzp** [comment]
It works now. thanks CovertJaguar for whatever you've done
