### ISSUE TITLE
Tracks Builder in ver Traincraft-4.3.0_003 is broken 

### ISSUE THREAD

**Issue by Netotorres** [Mrbrutal/Traincraft-5#38]
When the tracks builder places rail it uses 2 rails from the stack per block. The track builder it supposed use one rail from the stack per block.  It a bug in the subtraction of rail in the GUI it subtract by 2 rails from the stack instead of 1. When tracks builder is use it supposed to go 64 rails, 63 rails, 62 rails, 61 rails, but it goes 64 rails, 62 rails, 60 rails, 58 rails.

**Comment by NitroxydeX** [comment]
This can be closed because it is already fixed in the 1.7-repo

https://github.com/EternalBlueFlame/Traincraft-5/commit/d4a11991be150a8efa1465927633baa07d5c0cbb
