### ISSUE TITLE
Train will not move

### ISSUE THREAD

**Issue by CrazyPuffleGamer** [Mrbrutal/Traincraft-5#44]
I'm holding and pressing w, my fuel is full, the engine is on, and the brakes are off. Why is it not working??? :,(
(I'm on 1.7.10)

**Comment by canitzp** [comment]
please post this at the 1.7.10 issue tracker. it is at the fork of EternalBlueFlame

**Comment by CrazyPuffleGamer** [comment]
... I don't know the website.

**Comment by NitroxydeX** [comment]
https://github.com/EternalBlueFlame/Traincraft-5
