### ISSUE TITLE
diesel in openblocks tanks has glitched name

### ISSUE THREAD

**Issue by Nocty201** [Mrbrutal/Traincraft-5#48]
Image here: http://imgur.com/X5URvBA

The text is, as expected, doing the cycling glitchy thing. Latest version for 1.7.10

To reproduce:

Cook some sugar in the still, pipe it out with an Enderio Conduit into an openblocks tank. Look at the tank with NEI.

**Comment by EternalBlueFlame** [comment]
The github for 1.7 I over here
[https://github.com/EternalBlueFlame/Traincraft-5](https://github.com/EternalBlueFlame/Traincraft-5)

Also try running minecraft in a different language, see if that changes it.
It's likely the language file for your language doesn't have an entry for the diesel. Or it may not even exist in the first place.

**Comment by Nocty201** [comment]
Oops, thank you!
