### ISSUE TITLE
Configureable fluid production amounts in the still

### ISSUE THREAD

**Issue by Nocty201** [Mrbrutal/Traincraft-5#49]
Would it be possible to have configurable ratios for the still? One sugar cane into 1 bucket of diesel seems a little excessive. An entry in the config file would be nice. (Oh, and backport to 1.7.10 if you do add it, pretty please).

Thanks!

**Comment by EternalBlueFlame** [comment]
backporting it to 1.7 won't be an option because the code bases are VERY different, however I'll look into doing it from scratch for the 1.7 rewrite.
