### ISSUE TITLE
Composite Suit Durability

### ISSUE THREAD

**Issue by iou1name** [Mrbrutal/Traincraft-5#55]
Whenever one of the Composite Suit's effects activate, such as the legs Jump Boost or the helm's Night Vision, part of that armor piece's durability is used. For example, every time I jump 40 durability is taken from legs; 1 durability is taken from the helm when night vision activates, 5 for water breathing. Additionally, any time the durability reaches zero or below **as a result of this phenomenon**, the durability is reset to full (or almost full). If the durability reaches zero due to damage taken (rather easy to happen with the legs degrading as fast as they do), the armor piece is destroyed.

I assume this to be a bug since the book description makes no note of it but then again the book description is brief to begin with and I've found little documentation elsewhere. If it is intentional it seems like something that ought be mentioned somewhere since this really kind of makes the whole armor set useless.

I'm using:
Minecraft 1.7.10
Forge 1.7.10-10.13.4.1614
Traincraft 4.3.1_007 (though I've the same happen on earlier versions including 4.3.0_003)

**Comment by EternalBlueFlame** [comment]
This is the wrong repository for 1.7, it was even added to the main page of this branch that 1.7 issues don't go here and a link to where they go....

And to be honest little documentation in general exists for TC, I'm not even fully sure how the thing is supposed to work. Although I'm sure the durability reset thing is a bug.

It's likely the issue has existed since 1.6.4, since the related code hasn't even been touched since.

**Comment by iou1name** [comment]
If you're talking about https://github.com/EternalBlueFlame/Traincraft-5, the front page of this repo only mentioned sending pull requests there. Unless I'm just blind the only mention of where to send Issues is "An issue system or website will be provided in due time. Possibly, we might just use the GitHub's own system."

If you'd like I can put this in that repo instead.

**Comment by EternalBlueFlame** [comment]
I see your point. I guess it should be elaborated a bit...
My mistake there aside, this issue tracker is used for the 1.11 version, and problems concerning 1.7 should be over on the repo you linked.
I'll try and make a pull request to fix the readme.

**Comment by iou1name** [comment]
Alright, I'll open an issue over there instead. Thanks for the clarification.

**Comment by EternalBlueFlame** [comment]
Sorry about all the confusion, and my mistake on the contents of the readme on this repo.
I sent in the pull request to change the readme just now. hopefully that will help to clear up the problem for others.
