### ISSUE TITLE
Traincraft Electric trains aren't compatible with Railcraft electric tracks

### ISSUE THREAD

**Issue by Bendragon1337** [Mrbrutal/Traincraft-5#60]
Hey there

The Traincraft Electric trains do not get electric power from Railcraft tracks.

**Comment by EternalBlueFlame** [comment]
the 1.7 issue tracker is over here: [https://github.com/EternalBlueFlame/Traincraft-5/issues](https://github.com/EternalBlueFlame/Traincraft-5/issues)
this was even noted in the readme.
