### ISSUE TITLE
Coupling issues with Minecarts and Minecart Haulers.

### ISSUE THREAD

**Issue by Bendragon1337** [Mrbrutal/Traincraft-5#61]
Hey there.

There's a glitch with the Minecart and Cart Hauler which are included within Traincraft in the fact that when the vehicles are coupled together, the vehicles merge into each other.

**Comment by canitzp** [comment]
Please post it at the 1.7 issue tracker: https://github.com/EternalBlueFlame/Traincraft-5/issues
