### ISSUE TITLE
Disabling traincraft recipes

### ISSUE THREAD

**Issue by Wahazar** [Mrbrutal/Traincraft-5#70]
I propose to add config option for disabling traincraft table and assembly table recipes, because there is no way to tweak them in case of well balanced modpacks.

**Comment by EternalBlueFlame** [comment]
Could just disable the tables themselves, if you're using stuff for tweaking recipes.

**Comment by Wahazar** [comment]
Sure, I can disable crafting of traincraft tables, but traincraft table recipes will still be visible and make mess in NEI.
Config option for disabling whole traincraft table would be welcomed.

**Comment by Wahazar** [comment]
Sorry, this issue should be addressed to 1.7.x branch, not 1.11
