### ISSUE TITLE
Ticking entity: tc.DD35 B Unit

### ISSUE THREAD

**Issue by epeeforteyt** [Mrbrutal/Traincraft-5#75]
Hello by here, this is my first time that I post a message of "bug / error" be indulgent :)

When I put this "entity" I crashed moment, I put you the error code in full pastebin https://pastebin.com/dR3wrxbM

Thank you

**Comment by EternalBlueFlame** [comment]
Thanks for the heads up, this bug has already been dealt with for the next release, sorry it's been so slow in development, there's been a lot of stuff getting in the way.

Also the repo you are looking for is over here:
https://github.com/EternalBlueFlame/Traincraft-5
The repo you're posting in now is more or less only for the release builds, not work that's currently being done.
