### ISSUE TITLE
[1.7.10] Problem with Assembly table I

### ISSUE THREAD

**Issue by demycat** [Mrbrutal/Traincraft-5#76]
There is a problem with the first assembly table does not craft Cart Hauler and Minecart (version 4.3.4_013)
![2018-03-21_19 47 11](https://user-images.githubusercontent.com/34833284/37728518-240988ae-2d43-11e8-9d0f-c18f76331481.png)
![2018-03-21_19 47 16](https://user-images.githubusercontent.com/34833284/37728519-243edb62-2d43-11e8-9573-0308c6bacbae.png)
And in the version 4.3.5_014, if you are trying to use the first assembly table, then the game hangs tightly

**Comment by demycat** [comment]
And assembly table II and III do not have any problems

**Comment by EternalBlueFlame** [comment]
NEI is bugged, for some odd reason the recipes don't always work, and are always on table 1.

**However** what you put in shouldn't have had any problem making the item.
It could be some sort of recipe conflict bug in 014, or something else, I have no clue, but it's totally fine in 015 so whatever it was, it got fixed.

also this is the github for the generally abandoned 1.10 rewrite, not the 1.7 port, which is over here:
https://github.com/EternalBlueFlame/Traincraft-5
![image](https://user-images.githubusercontent.com/9969122/37750115-4a293348-2d59-11e8-84dc-c009b3aef7b3.png)

**Comment by demycat** [comment]
@EternalBlueFlame  So in the book too it is written that in the first table it is necessary to do (in others it was not craft)
![2018-03-22_13 26 23](https://user-images.githubusercontent.com/34833284/37768019-ce102060-2dd4-11e8-8236-628f814bc9e9.png)

**Comment by demycat** [comment]
And this is version 013, and if I put 014, then when you open Assembly table I, the game freezes

**Comment by demycat** [comment]
@EternalBlueFlame You said that there is version 015, but it's not on the curse site

**Comment by EternalBlueFlame** [comment]
014 has a debug log function that gets called when the table is open, its not actually a freeze just a massive lag while it logs stuff, it _WILL_ unfreeze.
running the game under JDK 8 does help remove the issue.

As for version 015 it is not released yet, but if you're so adventurous you can grab the source code to compile from the link i posted earlier.

**Comment by demycat** [comment]
@EternalBlueFlame Game unfreeze in 30 minutes or 1 hour!
"running the game under JDK 8 does help remove the issue." How do I do this? (I installed the program)

**Comment by EternalBlueFlame** [comment]
ouch, even for JRE thats pretty bad, usually from testing I've seen before it's 10 to 15 minutes.

if you're using the default launcher you can change the working directory (where java is) in the arguments by adding it to the start in quotes, alternatively you can just change your default version of java by changing the "JAVA_HOME" folder to the JDK folder and restarting the computer, here's an image from mine if it helps any
![image](https://user-images.githubusercontent.com/9969122/37880995-821e2092-3056-11e8-90a2-1400b0f95aed.png)


Although if it's 30+ minutes in JRE, even from JDK I wouldn't get my hopes up too high.
One plus side though would be that with JDK as your default java, compiling the source code for 015 to an actual usable mod file is a lot easier (should just be able to download the zip, extract it somewhere, run the setup bat and choose build, although windows 10 users have to manually open powershell in the folder and run "gradlew build").
