### ISSUE TITLE
Recipe Book Crash at site 53

### ISSUE THREAD

**Issue by kuxii2016** [Mrbrutal/Traincraft-5#77]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 30.01.19 12:14
Description: Rendering screen

java.lang.NullPointerException: Rendering screen

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1464)

-- Screen render details --
Details:
	Screen name: train.client.gui.GuiRecipeBook
	Mouse location: Scaled: (377, 207). Absolute: (754, 64)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1464)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Kuxii'/180832, l='MpServer', x=-3048,99, y=69,62, z=1027,00]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-69,64,-88), Chunk: (at 11,4,8 in -5,-6; contains blocks -80,0,-96 to -65,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 54887281 game time, 60936615 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 71 total; [EntityCartChest['entity.MinecartChest.name'/2688, l='MpServer', x=-3042,50, y=44,50, z=1085,50], EntityCartChest['entity.MinecartChest.name'/180614, l='MpServer', x=-2987,50, y=46,36, z=1070,34], MoCEntityButterfly['ButterFly'/180875, l='MpServer', x=-3137,41, y=66,00, z=930,59], EntityZombie['Zombie'/181134, l='MpServer', x=-3017,50, y=47,00, z=1045,50], EntityZombie['Zombie'/181135, l='MpServer', x=-3016,50, y=47,00, z=1040,50], MoCEntityHorse['WildHorse'/180883, l='MpServer', x=-3072,97, y=70,00, z=934,13], EntitySkeleton['Skelett'/181014, l='MpServer', x=-3128,50, y=17,00, z=960,50], EntityCreeper['Creeper'/180887, l='MpServer', x=-3125,34, y=39,00, z=964,00], MoCEntityHorse['WildHorse'/2838, l='MpServer', x=-3151,59, y=64,00, z=1077,50], EntityClientPlayerMP['Kuxii'/180832, l='MpServer', x=-3048,99, y=69,62, z=1027,00], MoCEntityAnt['Ant'/104214, l='MpServer', x=-3012,66, y=70,00, z=1072,56], MoCEntityMouse['Mouse'/2839, l='MpServer', x=-2957,31, y=63,00, z=1133,53], MoCEntityBunny['Bunny'/2846, l='MpServer', x=-2994,44, y=71,00, z=1087,88], EntityCartChest['entity.MinecartChest.name'/2850, l='MpServer', x=-2948,50, y=40,50, z=1089,50], MoCEntityHorse['WildHorse'/2851, l='MpServer', x=-2947,88, y=66,00, z=1101,88], MoCEntityHorse['WildHorse'/2852, l='MpServer', x=-2944,50, y=66,00, z=1092,41], MoCEntityFly['Fly'/2857, l='MpServer', x=-3008,44, y=67,00, z=1124,09], MoCEntityCricket['Cricket'/2864, l='MpServer', x=-3079,41, y=69,00, z=1132,09], MoCEntityHorse['WildHorse'/2873, l='MpServer', x=-3070,50, y=69,00, z=1073,34], EntitySkeleton['Skelett'/180795, l='MpServer', x=-2985,50, y=33,00, z=960,50], MoCEntityKittyBed['entity.MoCreatures.KittyBed.name'/180664, l='MpServer', x=-3056,88, y=68,00, z=1022,84], MoCEntityPiranha['Piranha'/180665, l='MpServer', x=-3066,75, y=68,00, z=1034,19], MoCEntityCricket['Cricket'/2876, l='MpServer', x=-3089,13, y=66,00, z=1137,06], MoCEntityLitterBox['entity.MoCreatures.LitterBox.name'/180803, l='MpServer', x=-3055,09, y=72,00, z=1026,78], MoCEntityLitterBox['entity.MoCreatures.LitterBox.name'/180804, l='MpServer', x=-3055,94, y=68,00, z=1025,16], EntityItemFrame['entity.ItemFrame.name'/180805, l='MpServer', x=-3051,50, y=69,50, z=1024,94], MoCEntityHorse['WildHorse'/2896, l='MpServer', x=-3148,56, y=58,36, z=1130,13], MoCEntityHorse['WildHorse'/2897, l='MpServer', x=-3151,38, y=58,34, z=1129,91], EntityZombie['Zombie'/181331, l='MpServer', x=-3024,50, y=45,00, z=998,50], EntitySkeleton['Skelett'/180819, l='MpServer', x=-2971,84, y=12,00, z=1056,38], MoCEntityHorse['WildHorse'/2898, l='MpServer', x=-3141,56, y=63,00, z=1123,19], EntityZombie['Zombie'/181328, l='MpServer', x=-2987,50, y=41,00, z=1069,50], EntitySkeleton['Skelett'/181332, l='MpServer', x=-3028,50, y=45,00, z=998,50], MoCEntityHorse['WildHorse'/2776, l='MpServer', x=-3029,06, y=45,00, z=1097,34], EntityEnderman['Enderman'/180827, l='MpServer', x=-2973,28, y=27,00, z=985,63], EntityZombie['Zombie'/181339, l='MpServer', x=-3003,53, y=67,00, z=1095,97], MoCEntityMouse['Mouse'/180830, l='MpServer', x=-2965,63, y=64,00, z=971,47], EntityChicken['Huhn'/180828, l='MpServer', x=-2969,47, y=64,00, z=989,47], EntitySkeleton['Skelett'/181340, l='MpServer', x=-3006,50, y=68,00, z=1096,50], MoCEntityAnt['Ant'/180829, l='MpServer', x=-2967,44, y=64,00, z=987,44], MoCEntityGoat['Goat'/180834, l='MpServer', x=-3020,78, y=39,00, z=1049,88], MoCEntityKitty['Kitty'/180835, l='MpServer', x=-3076,35, y=67,44, z=996,35], MoCEntityKitty['Kitty'/180833, l='MpServer', x=-3064,00, y=69,00, z=999,00], MoCEntityHorse['WildHorse'/180838, l='MpServer', x=-3086,75, y=72,00, z=984,75], EntitySkeleton['Skelett'/180839, l='MpServer', x=-3121,41, y=48,01, z=1020,06], MoCEntityKitty['Kitty'/180836, l='MpServer', x=-3059,00, y=69,00, z=984,00], MoCEntityFly['Fly'/2790, l='MpServer', x=-3135,22, y=62,00, z=1114,47], MoCEntityKitty['Kitty'/180837, l='MpServer', x=-3102,88, y=63,00, z=1002,34], MoCEntityLitterBox['entity.MoCreatures.LitterBox.name'/2663, l='MpServer', x=-3050,25, y=80,00, z=1018,66], MoCEntityWerewolf['Werewolf'/180842, l='MpServer', x=-3051,72, y=24,00, z=947,53], EntityZombie['Zombie'/180843, l='MpServer', x=-3056,50, y=26,00, z=949,50], MoCEntityHorse['WildHorse'/180840, l='MpServer', x=-3070,28, y=73,00, z=974,19], MoCEntityFox['Fox'/2794, l='MpServer', x=-3000,44, y=66,00, z=1134,50], MoCEntityAnt['Ant'/180841, l='MpServer', x=-2995,44, y=67,00, z=995,44], MoCEntityHorse['WildHorse'/180846, l='MpServer', x=-3076,94, y=72,00, z=949,50], MoCEntityButterfly['ButterFly'/2796, l='MpServer', x=-2941,56, y=81,00, z=1128,66], EntityZombie['Zombie'/180847, l='MpServer', x=-3108,50, y=35,00, z=965,50], EntityZombie['Zombie'/180844, l='MpServer', x=-3056,50, y=26,00, z=950,50], MoCEntityHorse['WildHorse'/180845, l='MpServer', x=-3025,38, y=70,00, z=949,63], MoCEntityMediumFish['MediumFish'/180850, l='MpServer', x=-3113,62, y=62,00, z=962,73], EntityZombie['Zombie'/180851, l='MpServer', x=-3121,50, y=33,00, z=980,50], MoCEntityMediumFish['MediumFish'/180848, l='MpServer', x=-3106,22, y=62,00, z=965,31], EntityCreeper['Creeper'/181104, l='MpServer', x=-3114,50, y=15,00, z=952,50], MoCEntityMediumFish['MediumFish'/180849, l='MpServer', x=-3106,25, y=62,00, z=966,59], MoCEntityHorse['WildHorse'/180852, l='MpServer', x=-3147,28, y=63,00, z=1036,97], MoCEntityHorse['WildHorse'/2806, l='MpServer', x=-3049,19, y=71,00, z=1136,03], MoCEntityMaggot['Maggot'/2680, l='MpServer', x=-3077,47, y=69,00, z=1133,81], MoCEntityMaggot['Maggot'/2681, l='MpServer', x=-3089,22, y=66,00, z=1137,69], MoCEntityHorse['WildHorse'/2811, l='MpServer', x=-3056,81, y=50,00, z=1129,50], MoCEntityHorse['WildHorse'/2812, l='MpServer', x=-3058,28, y=50,00, z=1132,91], MoCEntityMaggot['Maggot'/2813, l='MpServer', x=-3071,19, y=69,00, z=1133,53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1308244880 bytes (1247 MB) / 3130523648 bytes (2985 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 103
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_E3 111 mods loaded, 102 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	mcdiscord{2.0.0} [MC Discord] (minecraft.jar) 
	UCHIJA	bspkrsCore{6.9} [bspkrsCore] ([1.7.2]bspkrsCore-universal-6.9.jar) 
	UCHIJA	Treecapitator{1.7.2} [Treecapitator] ([1.7.2]Treecapitator-universal-2.0.3.jar) 
	UCHIJA	IC2{2.2.828-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.828-experimental.jar) 
	UCHIJA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJA	AFSU{1.2.2a-Mustaa} [AFSU Mod] (AFSU-1.2.2a-Mustaa.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
	UCHIJA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJA	BuildCraft|Core{6.4.15} [BuildCraft] (buildcraft-6.4.15.jar) 
	UCHIJA	BuildCraft|Builders{6.4.15} [BC Builders] (buildcraft-6.4.15.jar) 
	UCHIJA	BuildCraft|Energy{6.4.15} [BC Energy] (buildcraft-6.4.15.jar) 
	UCHIJA	BuildCraft|Factory{6.4.15} [BC Factory] (buildcraft-6.4.15.jar) 
	UCHIJA	BuildCraft|Transport{6.4.15} [BC Transport] (buildcraft-6.4.15.jar) 
	UCHIJA	BuildCraft|Silicon{6.4.15} [BC Silicon] (buildcraft-6.4.15.jar) 
	UCHIJA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCHIJA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJA	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCHIJA	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
	UCHIJA	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal(1).jar) 
	UCHIJA	enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar) 
	UCHIJA	fgtXray{1.0.8} [Fgt X-Ray] (fgtXray-1.7.10-1.0.8.jar) 
	UCHIJA	Steamcraft{0.28.12} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.12.jar) 
	UCHIJA	ForgeEssentialsClient{1.4.5} [Forge Essentials Client Addon] (forgeessentials-1.7.10-1.4.6.1341-client.jar) 
	UCHIJA	IC2BackpackHUD{3.0} [IC2 Backpack HUD] (IC2 Backpack HUD v3.0 - MC 1.7.10.zip) 
	UCHIJA	IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2] (IC2NuclearControl-2.3.3a-Exist.jar) 
	UCHIJA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJA	ImmibisCore{59.1.2} [Immibis Core] (immibis-core-59.1.2.jar) 
	UCHIJA	ImmibisPeripherals{59.0.2} [Immibis's Peripherals] (immibis-peripherals-59.0.2.jar) 
	UCHIJA	IndustrialPeripheral{1.02} [Industrial Peripheral] (industrialperipheral-1.7.10-1.02public-universal.jar) 
	UCHIJA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (inventorytweaks1.7.10.jar) 
	UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJA	LogisticsPipes{0.8.3.106} [Logistics Pipes] (logisticspipes-0.8.3.106.jar) 
	UCHIJA	mm{1.7.10-1.1} [Minecraft Money] (MinecraftMoney-1.7.10-1.2-01.jar) 
	UCHIJA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHIJA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (MoCreatures.zip) 
	UCHIJA	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJA	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHIJA	OpenMods{0.10} [OpenMods] (OpenModsLib-1.7.10-0.10.jar) 
	UCHIJA	OpenPeripheralCore{1.4} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-8.jar) 
	UCHIJA	OpenPeripheralIntegration{0.6} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-8.jar) 
	UCHIJA	OpenPeripheral{0.6} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-8.jar) 
	UCHIJA	PneumaticCraft{1.12.3-146} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.3-146-universal.jar) 
	UCHIJA	PowerConverters{1.7.10_3.3.0-jenkins.74} [Power Converters] (PowerConverters-1.7.10_3.3.0-jenkins.74.jar) 
	UCHIJA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJA	ResourceLoader{1.3} [Resource Loader] (ResourceLoader-MC1.7.10-1.3.jar) 
	UCHIJA	signpic{2.8.0} [SignPicture] (SignPicture-1.7.10-2.8.0-universal.jar) 
	UCHIJA	signpost{1.07.2} [Signpost] (signpost-1.7.10-1.07.2.jar) 
	UCHIJA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJA	tc{4.4.1_019} [Traincraft] (Traincraft-4.4.1_019.jar) 
	UCHIJA	Uncomplication{0.1.2.1.b71} [Uncomplication] (Uncomplication-1.7.10-0.1.2.1.b71.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	xaerominimap{1.16} [Xaero's Minimap] (Xaeros_Minimap_FP1.16_Forge_1.7.10.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13544 Compatibility Profile Context 25.20.15011.1004' Renderer: 'AMD Radeon R9 200 Series'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	NetherOres: -[1.7.10]2.3.1-22
	ThermalDynamics: -[1.7.10]1.2.1-172
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon R9 200 Series GL version 4.6.13544 Compatibility Profile Context 25.20.15011.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)
	OptiFine Version: OptiFine_1.7.10_HD_U_E3
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13544 Compatibility Profile Context 25.20.15011.1004
	OpenGlRenderer: AMD Radeon R9 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by EternalBlueFlame** [comment]
This error belongs over on
https://github.com/EternalBlueFlame/Traincraft-5

In addition to that it's a conflict with computercraft that has been dealt with already for the next release.
