### ISSUE TITLE
Train Workbench can't be automated

### ISSUE THREAD

**Issue by JoseLgamer** [Mrbrutal/Traincraft-5#79]
I'm building  a base where everithing is automate and i tried multiple diferent ways to automate a train workbench. The problem lies in the fact that i didn't got any pipe from any mod to extract the final product. Putting items on the crafting grid works fine. I think the other mods are not recognizing the output slot and then don't extract the item from the train workbench. Hope it helps someone else.

**Comment by EternalBlueFlame** [comment]
there's a large number of issues with the crafting system that prevent this from working currently.
until the rewrite your best bet is going to be using MineTweaker to move the recipes over to a table that can be automated.

Also the main repo for TC development is over here if you're interested in delving into source >
[https://github.com/EternalBlueFlame/Traincraft-5](https://github.com/EternalBlueFlame/Traincraft-5)

This repo only contains the source for currently released versions.
