### ISSUE TITLE
So this was abuse was it?

### ISSUE THREAD

**Issue by infiniteblock** [Mrbrutal/Traincraft-5#80]
infinite05/17/2020
so the game will crash if he trys to play?
Green PC05/17/2020
no
he is banned from contrib
not from playing the mod
:cat_thonk:
Will the Mechanist05/17/2020
he isnt allowed to make things to put in the mod
infinite05/17/2020
i remember some code being added that stops people playing too...
Green PC05/17/2020
it is indeed possible
but Maz isn't banned from the mod
infinite05/17/2020
greg and all that had to stop using code like that due to violation of mojang's licence's
Green PC05/17/2020
unable to find anything about that
could you send any TOS that includes such info?
infinite05/17/2020
im not going reading it all
sebasver | WWCP05/17/2020
So
Green PC05/17/2020
i am unable to find anything about not allowing mods to ban people from playing them :cat_thonk:
sebasver | WWCP05/17/2020
You just throw in an a fact thats unproven
infinite05/17/2020
it is proven go ask greg
Green PC05/17/2020
If you comply with and follow the Essential Requirements (in the Brand and Asset Usage Guidelines) and Naming Guidelines above, YOU MAY distribute or make available plug-ins and other bits and pieces of extended functionality etc. that you create (together, "Mods") for free and without any charge, but not if the purpose of your Mod is to advertise or promote other products or services (see the section below on Building Promotions with Minecraft). By "Mods," we mean something original that you created that doesn't contain a substantial part of our copyrightable code or content. We have the final say on what constitutes a Mod and what doesn't. When you combine your Mod with the Minecraft software, we will call that combination a "Modded Version" of the Game. You MAY NOT distribute any Modded Versions of our Game or software, though you may distribute Mods. You may make money from Mods as described below in the section, "Servers and Hosting."
infinite05/17/2020
hes also not the only mod that was doing that
bigFISH496 | WWCP |05/17/2020
Nah bro, burden of proof is on you to back up your claim
Green PC05/17/2020
that is from the Terms and conditions of Mojang, nothing about not allowing to block certain people from playing your mod, especially if they have a good reason to be banned from the mod
if you want us to believe your statement, back up your claim
atm we will keep banning people who have a good reason to be banned. For example stealing of content, really toxic behaviour towards the community etc. unless you, or someone else proves that it is, in fact, against Mojang's rules
sebasver | WWCP05/17/2020
Yeh
Eddie Dalton | WWCP05/17/2020
You’ll get banned if you sell your mod and gets profit out of it. If it’s free download, then Mojang can’t ban.
broscolotos05/17/2020
You may make money from Mods as described below in the section, "Servers and Hosting."
sebasver | WWCP05/17/2020
Still no sign of mods being forbidden from banning users
infinite05/17/2020
have u got a link to the code that was added?
Eddie Dalton | WWCP05/17/2020
Yeah but not like sell Trains In Motion when it’s a mod. Then you make profit out of the mod it self. Hosting and servers are a different matter. But the mod itself must not be payware.
sebasver | WWCP05/17/2020
What code?
And why
broscolotos05/17/2020
where does it say that Eddie?
infinite05/17/2020
does it crash the game when the player is banned?
bigFISH496 | WWCP |05/17/2020
@EternalBlueFlame he can answer better than anyone
sebasver | WWCP05/17/2020
Why does that matter?
Eddie Dalton | WWCP05/17/2020
https://account.mojang.com/documents/minecraft_eula
Mojang Account
infinite05/17/2020
because if it crashes the game thats malicious
sebasver | WWCP05/17/2020
If the player is banned from playing the mod then he just has to delete the mod
infinite05/17/2020
if it "stops" them joining a server thats different
sebasver | WWCP05/17/2020
No lol
infinite05/17/2020
so its malicious code
sebasver | WWCP05/17/2020
Its all the same
infinite05/17/2020
no its not
your crashing the game
sebasver | WWCP05/17/2020
I think you goto look back the definition of malicious code
bigFISH496 | WWCP |05/17/2020
so?
infinite05/17/2020
hence why i ask whats the code do
sebasver | WWCP05/17/2020
Malicious code is when it brings harm to a users pc
bigFISH496 | WWCP |05/17/2020
why do you care?
ooooh, are you going to report us to mojang? how scary
infinite05/17/2020
it does bring harm it crashes mojangs game
sebasver | WWCP05/17/2020
No lol
Really
Green PC05/17/2020
i think that could in fact be a problem :cat_thonk: 
if it deliberately crashes their game, then maybe it could indeed be something Mojang could pick up on.
sebasver | WWCP05/17/2020
It brings no harm to any files on the hosts PC
infinite05/17/2020
its just like hypixel
how they could ban servers
they got told from mojang too
sebasver | WWCP05/17/2020
Hypixel is a server
How can a server ban a server
Tell me
I am curious
infinite05/17/2020
not hypixel sorry
that pokemon thing
Eddie Dalton | WWCP05/17/2020
Pixelmon
sebasver | WWCP05/17/2020
No pixelmon had different reasons
Pixelmon was violation of copyrights
infinite05/17/2020
pixlemon yeah thats it
no
sebasver | WWCP05/17/2020
Which is stated as not allowed in the TOS
infinite05/17/2020
it had code that could crash a server
bigFISH496 | WWCP |05/17/2020
riiiiiiight
infinite05/17/2020
your crashing a client with code
sebasver | WWCP05/17/2020
Why are you doing this infinite?
I wonder
infinite05/17/2020
lol
Green PC05/17/2020
unable to find any info about pixelmon crashing servers?
infinite05/17/2020
u didnt look very hard
Eddie Dalton | WWCP05/17/2020
I think coders in here knows more about Minecraft codes than general players
bigFISH496 | WWCP |05/17/2020
lol
Green PC05/17/2020
and as i said: if you want us to believe something Back up your claim
bigFISH496 | WWCP |05/17/2020
maybe you should back up your claims @infinite
Green PC05/17/2020
show us proof
sebasver | WWCP05/17/2020
Yeah
Eddie Dalton | WWCP05/17/2020
Yus
sebasver | WWCP05/17/2020
Thats how it should go
infinite05/17/2020
what do i need to backup
u have malicious code
sebasver | WWCP05/17/2020
Wheres your proof of that
Back
Up
infinite05/17/2020
lol
sebasver | WWCP05/17/2020
Your
Freaking claims
infinite05/17/2020
its in tc code
broscolotos05/17/2020
show where it describes malicious code
sebasver | WWCP05/17/2020
At this point you just turned into a troll
infinite05/17/2020
your code is malicious because it crashes mojangs code
bigFISH496 | WWCP |05/17/2020
all in favor of a nice fat mute?
sebasver | WWCP05/17/2020
If you are prepared to wreak havoc backup your things
Green PC05/17/2020
for example: give proof to "pixelmon crashing servers"
Give proof to "not allowed to ban people from mod"
infinite05/17/2020
lol
Green PC05/17/2020
besides
broscolotos05/17/2020
and where does it say that it is malicious
infinite05/17/2020
thats why i asked u
Eddie Dalton | WWCP05/17/2020
If it crashes your game, that could be that the MC version is not the one that the mod works for
broscolotos05/17/2020
you can say it is malicious all you want, but you can't provide where it says that
infinite05/17/2020
does it crash the client or stop them playing...
sebasver | WWCP05/17/2020
Stop them from playing
More like joining world
infinite05/17/2020
see that wasnt hard was it
sebasver | WWCP05/17/2020
It doesnt actually crash the game
Eddie Dalton | WWCP05/17/2020
Try look up at your version of MC and the TC mod before accusing
sebasver | WWCP05/17/2020
So
infinite05/17/2020
if its not crashing the game
sebasver | WWCP05/17/2020
Why
bigFISH496 | WWCP |05/17/2020
inb4 "my dad works at microsoft i can get you banned"
Eddie Dalton | WWCP05/17/2020
What a surprise!
My Mc with this mod did not crash!
Green PC05/17/2020
i have another urge to mute, this week
:cat_thonk:
infinite05/17/2020
i dont really care
bigFISH496 | WWCP |05/17/2020

Green PC05/17/2020
i mean, you claim something and don't give proof to any of your claims and expect us to believe you
infinite05/17/2020
end of the day i was questioning the code
Green PC05/17/2020
and then you argue
infinite05/17/2020
no
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/1411035-malicious-code-found-in-the-pixelmon-mod
Malicious code found in the pixelmon mod. - Mods Discussion - Minec...
Not too long ago it was found that malicious code was in the pixelmon mod. The pixelmon staff have a blacklist that can remotely shut down pixelmon servers. ...
Eddie Dalton | WWCP05/17/2020
No you just comes up with stupid accusations without knowing the facts
Green PC05/17/2020
Finally
bigFISH496 | WWCP |05/17/2020
took ya long enough
infinite05/17/2020
thats the first result on google...
not hard
Eddie Dalton | WWCP05/17/2020
You do know that Pixelmon is different from this mod right?
bigFISH496 | WWCP |05/17/2020
apparently pretty hard for you
infinite05/17/2020
no kidding
not hard for me i can use google fine
Eddie Dalton | WWCP05/17/2020
Just because it has malicious code, doesn’t mean that every MC mod has
bigFISH496 | WWCP |05/17/2020
lol, then why'd it take you 10 minutes to post the first result on google
sebasver | WWCP05/17/2020
The thing is when you make a claim
infinite05/17/2020
i was asking how tc is banning people
sebasver | WWCP05/17/2020
You have a moral obligation to post the backup
infinite05/17/2020
crashing or stopping them from playing
Green PC05/17/2020
i like how the post says that it isn't really malicious
infinite05/17/2020
it is
Eddie Dalton | WWCP05/17/2020
It ain’t
infinite05/17/2020
hence why mojang also got in

**Comment by infiniteblock** [comment]
EternalBlueFlame04/25/2019
nah, carts dont use a traditional inventory system. afik you cant do it with commandblocks because you have to use a variable in the entity not a normal command block method.

you can do it with custom NPC commands since those get full code access through runtime class compile.
infinite04/25/2019
oh ok
cheers
infinite05/17/2020
what a child.... and u wonder why you have no respect outside of traincraft
EternalBlueFlame05/17/2020
lol, kid i stopped caring years ago. if someone wanted to take this job and do it i'd have a party. but no one else is gonna do it, so you're stuck with me,
infinite05/17/2020
yep it shows
EternalBlueFlame05/17/2020
you cant prove your claims, so why are you bothering me and the rest of the community?
and by "why" i mean, dont.
infinite05/17/2020
i can you have the code in your mod
EternalBlueFlame05/17/2020
then provide the proof that its against the mojang license. or even the forge one.

you wont.
infinite05/17/2020
your literally breaking laws
EternalBlueFlame05/17/2020
prove it. show the law
"innocent until proven guilty" wheres the proof?
infinite05/17/2020
your crashing software
EternalBlueFlame05/17/2020
thats not proof of the law
infinite05/17/2020
i will take it up with curseforge
EternalBlueFlame05/17/2020
EternalBlueFlameToday at 4:02 PM
thats not proof of the law
infinite05/17/2020
ring a lawyer that deals with computer security cases tell them your distributing software that lets u crash people's games
ask them what your liable for
EternalBlueFlame05/17/2020
EternalBlueFlameToday at 4:02 PM
thats not proof of the law
infinite05/17/2020
well i dont know were i live do it
but under multiple sections of law in multiple countrys u are
EternalBlueFlame05/17/2020
saying it is doesn't mean it's proof.
proof is links and citation.
the fact you dont provide any links or citation even though you claim so many times how easy it is to search, is pretty telling you're just talking out your ass
infinite05/17/2020
if your that oblivious to how crashing someone else's software isnt illegal and malicious code......
no wonder you struggle
EternalBlueFlame05/17/2020
the fact you dont provide any links or citation even though you claim so many times how easy it is to search, is pretty telling you're just talking out your ass
infinite05/17/2020
u can only copy and paste?
is that why traincraft hasnt updated :/
EternalBlueFlame05/17/2020
can you only talk out your ass?
links and citation or gtfo
infinite05/17/2020
is that why traincraft hasnt updated :/
no code to copy/paste
the fact your so pissed proves a point
im not mad just giving you information
you have a legal team
use them
EternalBlueFlame05/17/2020
i am the legal team
the reason i say you need to prove your point is because i already did the research and know its BS
infinite05/17/2020
isnt that pyro
or what ever his name is
EternalBlueFlame05/17/2020
no.
infinite05/17/2020
you havent
u wouldnt be like this if u had
its a shame really
EternalBlueFlame05/17/2020
you wanna tell me what i have done when you cant even cite your claim? thats rich
infinite05/17/2020
seriously? how can u think what your doing ISNT ?
my god
ive worked in computer security/forensic's with copyright infringment
EternalBlueFlame05/17/2020
whether or not it's malicious behavior, there's no TOS or laws that state my method is illegal.
just because you dont like it, and its mean, doesn't mean it's ilegal.

additionally if you actually did work in computer security you wouldnt have to ask where the code is. its not hidden at all, if you understand any syntax and do a little reading its pretty obvious.


continue to argue this pointless BS without providing citation and i can have you added to the list as well. im really not in the mood to play games with some snot-nosed wanabe keyboard warrior.
infinite05/17/2020
i cbf going over your code
i looked at it when u put it in
thats what a year ago?
snot nosed wanabe keyboard warrior lmao
thats your every time your on forge forums
EternalBlueFlame05/17/2020
oh really? then what class is it in?
infinite05/17/2020
:stuck_out_tongue:
like i said its a year ago
why would i remember
EternalBlueFlame05/17/2020
you're the one trying to argue this point. you should be prepared to provide proof you arent full of shit
infinite05/17/2020
why do i need to look at your code to prove its in it?
the fact it is and with screenshots of all this for curse...
the fact u run to insults ect
my god tc is toxic
people wonder why i cbf with tc anymore
the toxic waste runs from the top
infinite05/17/2020
btw
your code violates cf tos
your project will be getting removed as its a violation of the tos
:wink:
maybe join the cf discord :slight_smile:
EternalBlueFlame05/17/2020
citation or literally not worth my time
also added you to that banlist. enjoy :wink:
infinite05/17/2020
good for u
i make more money than you so buying a new account isnt a issue
i have a few anyways
but this also shows how pathetic you are
i point out what your doing is wrong
EternalBlueFlame05/17/2020
i have more info than just the account UUID.
i can ban you and your dumb kid 6 ways till sunday
infinite05/17/2020
so u ban me
EternalBlueFlame05/17/2020
you harassed me and the userbase and refused to give actual reason for your point besides your word
infinite05/17/2020
whoop de do ip address
EternalBlueFlame05/17/2020
and your word is less than worthless
infinite05/17/2020
no i told u what u were doing is wrong
you decided to be a tosser
EternalBlueFlame05/17/2020
says the tosser that's about to be banned not just from the mod but most of the community.
i'll be sure other communities like IR know about this as well
infinite05/17/2020
what that u had malicious code
EternalBlueFlame05/17/2020
a crash, intentional or not isnt malicious code. sorry that your autism damages your understanding of a TOS
i just feel bad for your kid.
he'd gonna grow up in such a shit enviornment. you're a horrid example
infinite05/17/2020
lmao
look at you

**Comment by canitzp** [comment]
There are some points your got wrong the whole time:
1. Writing a mod and distributing isn't against the EULA of Mojang, no matter what code it contains.
2. Crashing software isn't illegal at all. In fact Minecraft crashes itself under certain circumstances, like when a server tick exceeds it's maximum time. Also Forge does crash the game when problems like missing mod libraries are found.
3. Pixelmon was shut down, but not because it has malicious code. In fact malicious code can be in any mod, because it doesn't violate the EULA of Mojang. It was discontinued because the legal team of Nintendo wrote the creators of the mod, that they'll start going to take legal actions against them, when they don't stop with mod distribution.
4. I don't know what malicious code means for you, but for me it means that a piece of Software includes code that can harm the end user. Traincraft had crashing code. It doesn't harm the end user at all. It would harm when it deletes files on the pc, without asking.
5. Now we can come to the point where this kind of does violates a ToS, it's the one from CurseForge, so our main distribution platform. I haven't seen where they stated it, but they made it clear in temporarily suspending our page. Like you can see right now, it is back up and like before. Yes the versions with crashing code are re-uploaded without it, but that we are back up so fast shows that this incident wasn't bad at all. 

If you have more questions, just ask and I try to answer them, but when you claim some shit this time, please put some kind of proof besides it.
Your actions harmed Traincraft s lot. Maybe you should rethink your actions and maybe you say sorry for doing this. There're other ways to fix these issues.

**Comment by infiniteblock** [comment]
1, I never said it was against any EULA to distribute it.

2 Your crashing the game on purpose via an illegal blacklist

3 https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/1411035-malicious-code-found-in-the-pixelmon-mod

4 malicious code can be literally anything! you play a mod with the intention of having a good experience next minute it crashes because u supplied a fact the developer didn't like.

5 https://account.mojang.com/documents/minecraft_eula

"CONTENT
If you make any content available on or through our Game, you agree to give us permission to use, copy, modify, adapt, distribute, and publicly display that content. This permission is irrevocable, and you also agree to let us permit other people to use, copy, modify, adapt, distribute, and publicly display your content. You are not giving up your ownership rights in your content, you are just giving us and other users permission to use it. For example, we may need to copy, reformat, and distribute content that you post on our website so others can read it. If you don't want to give us these permissions, do not make content available on or through our Game. Please think carefully before you make any content available, because it may be made public and might even be used by other people in a way you don't like."
 

maybe accept my discord friend request so we can have a decent conversation?

**Comment by Green-PC** [comment]
3. https://kotaku.com/popular-pokemon-minecraft-mod-gets-shut-down-1796918730
    https://www.polygon.com/2017/7/14/15972052/pixelmon-minecraft-mod-shutdown
    https://www.pcgamer.com/pixelmon-the-pokemon-mod-for-minecraft-has-been-shut-down/

**Comment by canitzp** [comment]
1. You understand and it's done.
2. Crashing Software on purpose is normal. The blacklist itself isn't illegal, since it's our right as developer and programmer to do what we want.
3. I didn't even know that Pixelmon can do this, but I played it back then and I was sad when I read that it was stopped developing due to copyright claims from Nintendo. There was no word saying something about malicious code. But this is also done, since it is another mod.
4. Like I stated in 2, it is our right as developer to create what we want and what we think is right. I'm not saying that I support these kind of behaviors, I'm in fact completely against player blocking, but we can program it. There're things we can't do, like distributing the mod with such code on curseforge.
5. Idk what you want to say here. The citation doesn't say anything about malicious or game crashing code. They just say that they can freely use mods code in Minecraft without asking.

**Comment by infiniteblock** [comment]
You are REMOVING mojangs right to allow anyone to play the game when u add your own black list this is a breach of the EULA....

**Comment by Green-PC** [comment]
4.

From **Oxford Student's Dictionary**

**Malice:** The desire to harm others
**Malicious:** Feeling, Showing, caused by malice

5.
We are not removing Mojang's right to allow anyone to play, because _if_ Mojang would tell us that they want to give someone permission to use it, we would give them permission. As we are only breaching the EULA _if_ Mojang decides to give it to someone who is banned from the mod without us removing the code.

**Comment by infiniteblock** [comment]
anyone who purchases the game has been given permission...

**Comment by Green-PC** [comment]
may i ask where it says that?
