### ISSUE TITLE
Think about changing Oil to a fluid

### ISSUE THREAD

**Issue by NitroxydeX** [Mrbrutal/Traincraft-5#9]
[this should get marked with an idea tag]

You can't really say that Oilsand is not realistic it is but from my point of you Oil as a fluid would get this thing to a whole new level. It opens the thing to more mods which are working with fluids.

Since Oil is needed as a Tier 2 part you could transport it with a fluid wagon and your coal Trains. There could also be more possible ways to get a bigger amount transported without a train.

**Comment by EternalBlueFlame** [comment]
This is already done by a number of mods, and the main problem is that its used a lot as a burnable for a number of things, like coal, so a liquid would mean changing a lot of that and making an inability for it to power steam trains.
not to mention most people are already going to have a mod that does what you describe
[http://ftbwiki.org/Oil](http://ftbwiki.org/Oil)

**Comment by EternalBlueFlame** [comment]
well you have to keep in mind for when other mods add oils, because they will come to 1.9 eventually.
http://ftbwiki.org/Oil
Plus it will break use with steam trains, and require a re-design of the stuff that uses it.

Perhaps maybe a machine that can turn it into an oil fluid...?

**Comment by NitroxydeX** [comment]
@EternalBlueFlame This Are things a rewrite should deal with. Shouldn't conflict with other mods. Just register it to the OreDictionary and you can use it anywhere. 
Why it should break Steam trains? You never use Oil or Diesel in Steam trains. You can turn the Oil into Diesel with a machine like you do it atm.

**Comment by canitzp** [comment]
@NitroxydeX There is nor OreDict for Fluids... if one mod add an fluid with the same name like the other some things don't work

**Comment by NitroxydeX** [comment]
That's why Lex is always angry with devs...

![wp_ss_20160514_0001](https://cloud.githubusercontent.com/assets/9305576/15270704/134c72ee-1a29-11e6-825b-204a327af133.png)

And same fluids won't blocking each other anymore

**Comment by EternalBlueFlame** [comment]
You have a good point, we really shouldn't have oil sand work with steam trains in the first place, and even though a number of other mods add oil spouts, we can just set it up to disable oil spouts if another mod has it enabled. that way there's no oil spouts in your oil spouts.

**Comment by Mrbrutal** [comment]
Oli is a liquid. But oilsand is not. You get oil from oilsand by refining it. You then get fuel by refining oil. You can have both liquid and a block. That's how it was done in the older versions.

**Comment by NitroxydeX** [comment]
@EternalBlueFlame Why there should be Oilsprouts id your Oilsprouts? You can check for that on generation. So: No Problem. But yeah, maybe when Buildcraft is present it could be turned off.

@Mrbrutal thats correct. Thats why I said think about it. I think Liquids are always better than Blocks, so we should have just one of them.

**Comment by EternalBlueFlame** [comment]
What I meant was if we did gen the liquid oil in the world, we would have to check if there is another mod generating oil in the world, to make sure there's a balance and not an over-abundance.
with oil in an even more crude form, such as sand, where its even more effort to refine, it makes it a little more balanced with both.

Plus we have to add extra generation precautions to be sure it doesn't spawn near other liquids, because we all know how poorly oil and other liquids interact.

**Comment by gallopinggoose6** [comment]
Another way of handling this would to simply just make build craft a required mod for this which already has oil as a liquid. I believe that build craft already has a way to check, and deal with the problem you have described. I'm not a contributor, I'm just making a suggestion

**Comment by EternalBlueFlame** [comment]
we shouldn't make buildcraft required because there are a lot of servers that don't/wouldn't use it. which really limits the userbase.
on top of that, this is the 1.9 branch, does buildcraft even have a 1.9 version yet?

**Comment by gallopinggoose6** [comment]
it almost has it, they've been working on a 1.9 version for at least 2 months now
However, you do have a good point.

**Comment by gallopinggoose6** [comment]
Perhaps the issues should be filled up with bugs, rather than stuff people want to add, might make a working version of traincraft come sooner

**Comment by EternalBlueFlame** [comment]
Can't have any bugs without any features. (thats basically the current status of 1.9)

**Comment by gallopinggoose6** [comment]
well, what do you want coded first?

**Comment by EternalBlueFlame** [comment]
I'm mostly an adviser here, the one actually making the decisions and pull merges is @canitzp so the question should go to him.

**Comment by canitzp** [comment]
So my new plan is to implement oil as fluid and instead of getting diesel from oilSand in the distil you get the oil itself and have to refine this to diesel or refinedFuel

**Comment by canitzp** [comment]
I implemented Oil as fluid now but I don't replace the oil sand with it

**Comment by canitzp** [comment]
I think it's now time to close this. Oil is now implemented beside oil sand
