### ISSUE TITLE
My content is still in the 1.12.2 branch, despite me asking for it removed.

### ISSUE THREAD

**Issue by broscolotos** [Mrbrutal/Traincraft-5#90]
I requested that my content get removed on the 12th of July, and it is still in more than two weeks later. I'll post the list again here, but I would like this content removed within the next two weeks.

models:
JNR C62 (this was a model I made to replace the original)
JNR C62 tender (this was a model I made to replace the original)
JNR D51(long streamlining)
JNR D51(Short streamlining)
JNR D51 tender
Freight Wellcar(this was a model I made to replace the original)
King Class
Hall Class
4000 ton tender
Depressed Flatbed. Along the lines of removing this, there are 3 tank models that need removed as well. They are the CharB1, FT17, and the PanzerI.
Hiawatha locomotive
Hiawatha tender
Hiawatha baggage car
Hiawatha Passenger car
Hiawatha Beavertail car
GS4 Daylight Chair-Baggage car
GS4 Daylight Passenger
GS4 Daylight Tavern Car
GS4 Daylight Passenger Tail car
Propaganda cart (US)
Propaganda cart (USSR)
Propaganda cart (Britain)
Propaganda cart (Japan)
Three Dome Tanker
100 Ton Hopper
Generic Freight Bogie
GS4 bogie
Bulkhead Flat Cart

Textures:
All of the textures for the content listed above should probably be removed aswell.
White and Black on the BR Mk1
CSX skin for Box Cart US
CSX skin for the original Freight Wellcar
CSX skin for Tank Wagon US
red skin for the original JNR C62
red skin for the original JNR C62 tender
Blue texture for the A4 Mallard
Blue texture for the A4 Mallard tender
Union Pacific skin for the EMD F7
Union Pacific skin for the EMD F7B
Union Pacific skin for the EMD F3
Union Pacific skin for the EMD F3b

**Comment by canitzp** [comment]
Of course it is. We haven'T started to sort out which models we can and which we can't use. No worries, since we have a new renderer we have to convert every model by hand to the new format. When doing this we sort out all trains that aren't 1.6.4 content. This isn't gonna happen withing the next two weeks

**Comment by canitzp** [comment]
In the cleanup commit I did, your models are removed
