### ISSUE TITLE
High Star Switch Stand may need removal?

### ISSUE THREAD

**Issue by MadFrogs1** [Mrbrutal/Traincraft-5#91]
Hey,
I was looking through the code in src/main/resources/assets/traincraft/lang/en_us.lang and found a line containing lang info for the switch stand. The switch stand was actually added in traincraft 015 for 1.7.10 and did NOT feature in the 1.6.4 update, so it will probably need to be removed too.

**Comment by canitzp** [comment]
What was its purpose? I just ported it, but I never jnew what is was and how it behaves.

**Comment by MadFrogs1** [comment]
It's purpose is to switch junctions. When right clicked, the main shaft turns and the junction switches.

**Comment by canitzp** [comment]
So a replacement for the lever/redstone system used before?

**Comment by MadFrogs1** [comment]
Yes
The lever still works in the 1.7.10 version though, so it isn't a necessary item.

**Comment by canitzp** [comment]
Okay, so I'll remove it. It may be implemented later on from scratch
